### ISSUE TITLE
Example of how to use SvelteKit + Electron-Vite

### ISSUE THREAD

**Issue by dj-nuo** [alex8088/electron-vite#145]
### Clear and concise description of the problem

Currently electron-vite supports a list of frameworks, but SvelteKit is not in the list. Would be great if you can provide an example of how to use it with SvelteKit or NextJS.

### Suggested solution

I tried following https://evite.netlify.app/guide/project-structure.html#customizing-project-structure , but without any luck.
As far as I understand, I need to point Electron-Vite to build directory of SvelteKit, but I don't really understand how to configure SvelteKit, since it's controlled by electron.vite.config.ts

### Additional context

Sorry, if it's a dumb question. Still newbie here.

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-vite/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-vite/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://evite.netlify.app).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-vite/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
Learn more about https://evite.netlify.app/guide/#scaffolding-your-first-electron-vite-project

```bash
npm create @quick-start/electron
```
and select svelte template

**Comment by dj-nuo** [comment]
> Learn more about https://evite.netlify.app/guide/#scaffolding-your-first-electron-vite-project
> 
> ```shell
> npm create @quick-start/electron
> ```
> 
> and select svelte template

Yeah, that's what I did initially, and selected Svelte + TS. It works with regular Svelte, but I want to make it work with **SvelteKit**

**Comment by alex8088** [comment]
@dj-nuo ，

1. Run  `npm create svelte@latest my-app` to create a `SvelteKit` project. 
2. Replace the template's renderer directory
3. Update config:

modify `electron.vite.config.ts` to use `sveltekit  vite plugin` instead of `@sveltejs/vite-plugin-svelte`: 

```ts
import { defineConfig, externalizeDepsPlugin } from 'electron-vite'
import { sveltekit } from '@sveltejs/kit/vite'

export default defineConfig({
  main: {
    plugins: [externalizeDepsPlugin()]
  },
  preload: {
    plugins: [externalizeDepsPlugin()]
  },
  renderer: {
    plugins: [sveltekit()]
  }
})
```

modify `svelte.config.mjs ` to use `vite preprocess` instead of `svelte preprocess`:

```ts
import adapter from '@sveltejs/adapter-auto';
import { vitePreprocess } from '@sveltejs/kit/vite';

/** @type {import('@sveltejs/kit').Config} */
export default {
  // Consult https://kit.svelte.dev/docs/integrations#preprocessors
  // for more information about preprocessors
  preprocess: vitePreprocess(),

  kit: {
    // adapter-auto only supports some environments, see https://kit.svelte.dev/docs/adapter-auto for a list.
    // If your environment is not supported or you settled on a specific environment, switch out the adapter.
    // See https://kit.svelte.dev/docs/adapters for more information about adapters.
    adapter: adapter()
  }
};

export default config
```

4. Install related dependencies of sveltekit.

**Comment by dj-nuo** [comment]
Tried to do as you wrote in 10 different ways, but still no luck :'-(
I think the issue is that SvelteKit doesn't provide `index.html`, and overall is not as simple as Svelte as it would probably require `static` adapter if used with Electron.

If you managed to make it work - please share the template repo.

In the meantime, I also tried to build SvelteKit with `adapter-static`, which generates a directory with `index.html` in it & copied it into `renderer` folder. Still no luck((

**Comment by alex8088** [comment]
```
.
├──electron
│  ├──main
│  │  ├──index.ts
│  │  └──...
│  └──preload
│     ├──index.ts
│     └──...
├──src
├──static
├──electron.vite.config.ts
├──svelte.config.mjs
├──package.json
└──...
```

```ts
import { resolve } from 'path'
import { defineConfig, externalizeDepsPlugin } from 'electron-vite'
import { sveltekit } from '@sveltejs/kit/vite'

export default defineConfig({
  main: {
    plugins: [externalizeDepsPlugin()],
    build: {
      rollupOptions: {
        input: {
          index: resolve(__dirname, 'electron/main/index.ts')
        }
      }
    }
  },
  preload: {
    plugins: [externalizeDepsPlugin()],
    build: {
      rollupOptions: {
        input: {
          index: resolve(__dirname, 'electron/preload/index.ts')
        }
      }
    }
  },
  renderer: {
    plugins: [sveltekit()]
  }
})
```

```ts
import adapter from '@sveltejs/adapter-auto'
import { vitePreprocess } from '@sveltejs/kit/vite'

export default {
  preprocess: vitePreprocess(),
  kit: {
    adapter: adapter()
  }
}
```

It can work in development but not production.

1. SvelteKit requires `type: "module"`, but Electron does not support this.
2. SvelteKit enforces vite build target to `node`, which does not match the Electorn renderer.

So，I don't think it's possible to make `SvelteKit` work in Electron.

**Comment by dj-nuo** [comment]
### Part 1
**Is there a way to prevent `renderer` part of the `electron.vite.config.ts` from starting?** 
Meaning that electron part of things will continue to work as before, but:

In dev:
- in my `main` `index.ts` I will point to URL of dev server of `SvelteKit` (which I can start e.g. with `concurrently`, not with electron-vite command).

In prod (built):
- electron-vite will build only `main` and `renderer`, and then I will manually (through some script) copy result of my SvelteKit build into `out/renderer` directory.
-------------------------------------
### Part 2
Another option that I experimented with today was using this structure:
```.
├──electron
│  ├──main
│  │  ├──index.ts
│  │  └──...
│  └──preload
│     ├──index.ts
│     └──...
├──src
├──static
├──electron.vite.config.ts
├──svelte.config.mjs
├──package.json
└──...
```

`svelte.config.mjs` - added `adapter-static` for SvelteKit, which generates static html/css/js files, and doesn't require Node (!)
```
import adapter from '@sveltejs/adapter-static'
// import preprocess from 'svelte-preprocess'
import { vitePreprocess as preprocess } from '@sveltejs/kit/vite'

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: [
		preprocess({
			postcss: true
		})
	],

	kit: {
		adapter: adapter({
			fallback: 'index.html',
			pages: 'build-sveltekit', 
			assets: 'build-sveltekit'
		}),
		prerender: { entries: [] }
		// outDir: 'testDir'
	}
}

export default config

```

`electron.vite.config.ts` modified as following:
```
import { defineConfig, externalizeDepsPlugin } from 'electron-vite'
// import { svelte } from '@sveltejs/vite-plugin-svelte'
import { sveltekit } from '@sveltejs/kit/vite'
import { resolve } from 'path'

export default defineConfig({
	main: {
		plugins: [externalizeDepsPlugin()],
		build: {
			rollupOptions: {
				input: {
					index: resolve(__dirname, 'electron/main/index.ts')
				}
			}
		}
	},
	preload: {
		plugins: [externalizeDepsPlugin()],
		build: {
			rollupOptions: {
				input: {
					index: resolve(__dirname, 'electron/preload/index.ts')
				}
			}
		}
	},
	renderer: {
		plugins: [sveltekit()]
	}
})
```

**Now comes the interesting part:**

If my `package.json` had `"type": "module"`
```
{
	...
	"main": "./out/main/index.js",
	"type": "module",
	...
	"scripts": {
		...
	},
	"dependencies": {
		...
	},
	"devDependencies": {
                ...
		"@sveltejs/adapter-static": "^2.0.1",
                ...
	}
}
```
, then I could build my SvelteKit application into static files which will be saved in `build-sveltekit` folder as stated in `svelte.config.mjs`.

But, as you mentioned, 
> SvelteKit requires type: "module", but Electron does not support this.

... which raises the question: 
Maybe it's possible to have separate `package.json` for renderer part of things? (especially since renderer files are not Bytecoded or anything, they are just built to minified/uglified HTML/CSS/JS ). And this question is kind of related to **"Part 1"**

-------------------------------------
n.b. I really want to make it work, since electron-vite looks like an amazing project (actually one of it's kind) that makes "Bytecode" for Electron setup-free ^_^

**Comment by dj-nuo** [comment]
### Update & possible resolution: 
I managed to make it all work together by disabling `renderer` part of `electron-vite`.
Now the whole build configuration is handled by SvelteKit itself - it builds static files & places them into `out/renderer` directory.
Please, see this repo for better explanation of how it works - [dj-nuo/electron-vite-sveltekit-template](https://github.com/dj-nuo/electron-vite-sveltekit-template).
You can go through commits to see how I went step by step, starting from generating template with `npm create @quick-start/electron`

**Comment by alex8088** [comment]
👍 You found a new way，good work!
